alpha=0
beta=pi/2
factor_beta=0
angle = merge_angles(alpha, beta, factor_beta)
@test angle ≈ 0 atol=1e-8
factor_beta=1
angle = merge_angles(alpha, beta, factor_beta)
@test angle ≈ pi/2 rtol=1e-8
factor_beta=0.5
angle = merge_angles(alpha, beta, factor_beta)
@test angle ≈ pi/4 rtol=1e-8
angle = merge_angles(alpha, beta+2pi, factor_beta)
@test angle ≈ pi/4 rtol=1e-8
angle = merge_angles(alpha, beta-2pi, factor_beta)
@test angle ≈ pi/4 rtol=1e-8