name = "WinchControllers"
uuid = "9e74470a-8ab1-4f32-b878-f32ebd236ea2"
authors = ["Uwe Fechner <u.fechner-1@tudelft.nl> and contributors"]
version = "1.0.0-DEV"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
Parameters = "0.12.3"
StructTypes = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
